variable "instance_types" {}
variable "capacity_type" {}
variable "ami_type" {}
variable "vpc_cidr" {}
variable "dns_hostnames" {}
variable "dns_support" {}
variable "pub_one_cidr" {}
variable "pub_two_cidr" {}
variable "priv_one_cidr" {}
variable "priv_two_cidr" {}
variable "cluster_name" {}
variable "eks_version" {}
variable "region" {}